### ISSUE TITLE
not playing mp3 on android

### ISSUE THREAD

**Issue by totherpage95** [cguZZman/plugin.onedrive#10]
i was able to logon to onedrive for business but when i opened the music player on android it only shows mp3 music and not the m4a or wma audio. also on android it doesn't play the mp3 songs (but it does play them on desktop kodi).

**Comment by cguZZman** [comment]
@totherpage95 I confirmed m4a files are not being displayed. I'll fix it soon.
But mp3 files in android should be playing just fine. I tested it in my android and worked as expected.
Which android device you are playing it on?

**Comment by cguZZman** [comment]
Fixed with version 2.0.1 and using the `script.module.clouddrive.common` version 1.0.2.
