### ISSUE TITLE
cant see access photos that are shared with me

### ISSUE THREAD

**Issue by M0ti0n** [cguZZman/plugin.onedrive#11]
Hi
I installed the one drive plug in for kodi. I manage to log in fine. but I cant see or access photos that are shared with me. got some error wrong or bad argument,...

**Comment by cguZZman** [comment]
Can you please post the log of your Kodi so I can see what's happening? You can follow these steps: https://kodi.wiki/view/Log_file/Easy
And then paste here the link you your log file.

**Comment by cguZZman** [comment]
I'm gonna close this issue. If is still happening, please make sure you post your debug log file (debug logging enabled) and I will reopen it.
