### ISSUE TITLE
[MULTI ACCOUNT] Disconnect

### ISSUE THREAD

**Issue by tperraut** [cguZZman/plugin.onedrive#12]
Hi,
First of all, thank you so much for the awesome work you did.

I have 2 accounts added with a lot of movies in them (~300 per account).  And I noticed two bugs :
- When all movies are in one folder, the request to the server seems to time out and nothing happens. So I split my movies in alphabetical subfolders and it works just fine :)
- One of my account "disconnect" every day and when I go to Extension->Onedrive->MY_ACCOUNT->Files it prompts the message "file or directory not found" and the only solution I found is to disconnect and reconnect that account...

Thank you for taking time on that awesome extension !
Regards

**Comment by cguZZman** [comment]
@tperraut thanks for the report.
Can you help me with the logs of your Kodi? So I can know what's the real exception. You can follow these steps: https://kodi.wiki/view/Log_file/Easy
Let me know.

**Comment by tperraut** [comment]
http://ix.io/16KV

Thank you for your time

**Comment by tperraut** [comment]
@cguZZman did you figure out what happened or do you need help for it?

**Comment by cguZZman** [comment]
@tperraut the posted log file doesn't provide enough information because the debug logging was not enabled (step to in https://kodi.wiki/view/Log_file/Easy). 
Please post again a log file with debug info.

**Comment by cguZZman** [comment]
I'm gonna close this issue. If is still happening, please make sure you post your debug log file (debug logging enabled) and I will reopened.
