### ISSUE TITLE
 Authentication failed

### ISSUE THREAD

**Issue by JohnJohn45** [cguZZman/plugin.onedrive#13]
Hello I have this issues after enter the herokuapp code, onedrive login and password.
I replace some number and letter with XXXX because I don't know if it's secure.

Config : OSMC 17.6 on rasberry Pi 2

I test with Firefox on my phone and Firefox PC and edge on PC, same problem.

Sorry for my poor english.

Page : https://kodi-login.herokuapp.com/callback

Authentication failed:

{"error":"invalid_request","error_description":"AADSTS90002: Tenant XXXXXXXXXXXXXXXXXXXXX not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: XXXXXXXXXXXXXXXX\r\nCorrelation ID: XXXXXXXXXXXXX\r\nTimestamp: 2018-04-06 11:12:52Z","error_codes":[90002],"timestamp":"2018-04-06 11:12:52Z","trace_id":"XXXXXXXXXXXXXXXXXXXX","correlation_id":"XXXXXXXXXXXXXXXXXXXX"}

**Comment by cguZZman** [comment]
Can you please post the complete log of your Kodi so I can see what's happening? You can follow these steps: https://kodi.wiki/view/Log_file/Easy
And then paste here the link you your log file.

**Comment by JohnJohn45** [comment]
Thank you for your quick response. Problem is solved. I try it again 1 hour later and no error.
