### ISSUE TITLE
Error message Unknown error: u '\ xdf' Please try again. What can I do ?

### ISSUE THREAD

**Issue by Collo1975** [cguZZman/plugin.onedrive#15]
I can not watch some movies. Here the Logfile : https://paste.kodi.tv/gifiyigaki. Here a Picture : 
![20180710_005921](https://user-images.githubusercontent.com/41028730/42482550-72937f60-83e8-11e8-899b-3f41a476aa6b.jpg)

Thanks !!

**Comment by thomasmaster** [comment]
I have the same issues.

**Comment by Collo1975** [comment]
@thomasmaster  Kommst Du aus Deutschland ?

**Comment by cguZZman** [comment]
The issue is fixed in my repository. https://github.com/cguZZman/repository.plugins
You can install my repository or wait for the update on the kodi repository.

**Comment by Collo1975** [comment]
Many thanks !!! It worked and the Movies are up and running again.
