### ISSUE TITLE
unknown error: extra data...

### ISSUE THREAD

**Issue by vladimir12332** [cguZZman/plugin.onedrive#16]
Hi,
my Onedrive was working perfect but now i get this message:
Unknown error: Extra data: line 22 column 2 - line 22 column 3 (char 3295-3296)
Please try again.

Here is my log file:
`http://paste.kodi.tv/abobiguyak`

**Comment by cguZZman** [comment]
I think I got that error once and then just tried again and worked. I think it happens when two different process tries to access and write the account configuration file at the same time. Maybe I need to change the way the account and export configuration is stored. 
Can you tell me if this is still happening to you?
Sadly, the debug log file is not enough to know what the problem in the configuration file is, because it's not printed in the log. 
One solution could be removing the account file, and then add your accounts again. This will not affect any other configuration.

**Comment by vladimir12332** [comment]
I didn't mention, I'm using android box. I've tried to reinstall plugin but no change. I couldn't even enter "add account" menu. So I have cleared all Kodi data and reinstalled plugin. Now everything works.
Maybe there were some leftover configuration file inside Kodi that should be manually deleted after uninstall?? That's only way to explain why error occures again...

**Comment by cguZZman** [comment]
You only needed to delete the accounts file, without doing anything else.

Anyway, I'll keep this issue open and when have enough time I'll change how the accounts are stored.

**Comment by vladimir12332** [comment]
Google drive addon has this: "Subtitles can be assigned automatically if a .str file exists with the same name as the video."
OneDrive doesn't?

**Comment by cguZZman** [comment]
It does.

**Comment by vladimir12332** [comment]
> It does.

i'm sorry, but it doesn't.
.mkv + .srt with same filename, in same onedrive folder... not working. google drive works perfectly.

**Comment by vladimir12332** [comment]
any progress?

**Comment by boytempp** [comment]
This morning I found same problem of unknow error:  Extra data : line 28 column 2 - line 37 column 2 (char 2053 -2285) too.  pls check my log file.
[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/4238846/kodi.log)

**Comment by boytempp** [comment]
now, i cannot play movie from cloud.  it's keep pop up this error.

**Comment by gabriellluz** [comment]
Same happens to me :( I'm using Android Box too. I don't know how I can grab the log file. Which folder??

**Comment by gabriellluz** [comment]
Ok, I'll look at it today. But I'm pretty sure I've done a clean Kodi install then it worked for a few days only to crash again.

**Comment by gabriellluz** [comment]
Done. Works fine, but I'll have to use it for a few days because I did this in the past and I remember it worked for one day only.

**Comment by 4nn4r3ll4** [comment]
> I just want to bundle this with other improvements before doing the release of the new version.
Thanks for the splendid add-on!
Any ETA for the fix/new version? I keep getting the Extra Data error every two login into Kodi and it's quite painful :)

**Comment by cguZZman** [comment]
fixed in latest version
