### ISSUE TITLE
Onedrive video issues

### ISSUE THREAD

**Issue by thomasmaster** [cguZZman/plugin.onedrive#18]
Can not play onedrive video any more for onedrive business account

**Comment by marvinantoinette** [comment]
I also get this error message when trying to play anything from my onedrive business account. In the browser it is all playing fine.

> file or folder not found. Make sure is still in your drive. Please try again.

Thank you.

**Comment by rodrigopill** [comment]
Same here!

**Comment by Syyed123** [comment]
any news on this please

**Comment by cguZZman** [comment]
Hi all, I've been very busy these days. Lot of work. If somebody want to help fixing issues, feel free to send PRs.
No ETA for this fix.

**Comment by cguZZman** [comment]
Can somebody post a debug log file for this issue, if it's still happening?

**Comment by cguZZman** [comment]
since nobody has attached a debug log file for this issue, will close it.
feel free to open a new one with all required information.
