### ISSUE TITLE
OneDrive for Business authorization won't work because no admin

### ISSUE THREAD

**Issue by gabe117** [cguZZman/plugin.onedrive#19]
My Onedrive for business account will not authorize this add-on because there is no admin for the account. There's no way for me to add an admin.

Would it be possible to allow access using a shared link to a folder that doesn't require authorizing?

I feel like this would be the safest way anyway to not need authorization in the first place and allow all types of users access to the add-on.

Thanks

**Comment by worldyouwyl** [comment]
Need it too,thanks

**Comment by cguZZman** [comment]
If you can share your folder with a personal account or another business account, that will solve your problem. You can add that other account in kodi and access the folder thru the Shared with me option.
The authentication protocol used by the addon is OAuth2, so an authorization by the admin to use the addon is required. There is no other way for the moment.
