### ISSUE TITLE
Resume points are no longer set in Kodi 18 on raspbian

### ISSUE THREAD

**Issue by cblogins** [cguZZman/plugin.onedrive#20]
After updating Kodi to 18.2 on a raspberry pi with raspbian, resume points for movies are no longer set and therefore it's no longer possible to continue watching a movie at the stop/resume point (log file below). It was working fine on kodi 17.6
Strangely for me only .mp4 videos are affected, whereas when playing .mkv movies the resume points are set correctly.
Maybe related is what is shown in the top right corner in kodi, when starting a movie: For .mkv files the library name of the movie is shown, but for .mp4 movies the file name is shown.?
Setup: I exported .strm files to a home folder and added that folder to the library.
While debugging I tried the scenario with the exact same files stored locally and everything was working as expected. But when playing them from onedrive the problem occurs so I'm assuming it might be related to this add-on.

1. Start watching a movie long enough to exceed the default resume point threshold (3 min I believe)
2. Stop the movie.
3. The movie should be marked as "in progress" and should also appear in the "In Progress" section of the movie home screen
4. It doesn't :)

**Your debug log file**
http://paste.kodi.tv/akogatacey.kodi
started movie at 14:25, skipped 10 minutes into the movie, stopped the movie at 14:29

Most importantly though, thanks a lot for this great add-on and again, more than happy to donate if I knew where to :)

Regards

**Comment by cguZZman** [comment]
can you let me know if this is still happening? I believe this was a Kodi issue, not the addon.

**Comment by cblogins** [comment]
Hi Carlos,
I tried to reproduce on kodi 18.5 and you seem to be right. Resume point are set correctly for all tested files and file types. Now I've got problem with receiving an error regarding subtitles, but I'll open a seperate issue for that.

Issue can be resolved, thanks for your effort and regards,
C
