### ISSUE TITLE
Playback repeatedly stops after about 40 minutes

### ISSUE THREAD

**Issue by treanord** [cguZZman/plugin.onedrive#22]
**Describe the bug**
Any movies I play from OneDrive fB stop in the middle of play regularly. I can usually just select the movie again and it will continue where it left on from, however it is very frustrating. I am using 18.3 although the same was happening with earlier versions.
I have tried this from 3 different Fire TV devices, 1 Windows machine and 2 different internet connections and they are all acting the same.

**To Reproduce**
1. add a source from OneDrive for Business
2. include the source in the library using http://localhost:8586
3. scan to the library
4. play any video and wait for it to stop playing after anywhere between 20 and 70 minutes but usually about 30-40 minutes

**Your debug log file**
https://paste.kodi.tv/obifariyaj.kodi

Many thanks

**Comment by Kjartansson** [comment]
I have the same problem

**Comment by notSignum** [comment]
Same problem here. Kodi 18.4 on Fire TV 4k. Same setup, only with personal OneDrive instead of buisness.

**Comment by tperraut** [comment]
Same issue with Mi TV Box S and personal OneDrive
@cguZZman what validation do you need ? :)

**Comment by cguZZman** [comment]
I need to validate it on my devices. Is the problem still happening? is it happening all the times?

**Comment by treanord** [comment]
The problem is still happening and yes, all the time.

**Comment by treanord** [comment]
> I need to validate it on my devices. Is the problem still happening? is it happening all the times?

Have you had a chance to take a look at this? PM me  if I can help in any way.

**Comment by cguZZman** [comment]
Can somebody post a debug log file for this issue. You need to activate debug mode, play the video, wait until it stops and post your debug log file here.

**Comment by treanord** [comment]
> Can somebody post a debug log file for this issue. You need to activate debug mode, play the video, wait until it stops and post your debug log file here.

Looks like the one from my original post has expired. I will have to set up my test system again. Will get back to you shortly,

**Comment by onutz** [comment]
OneDrive streaming plugin is no longer working, all the movies in OneDrive when tried to be played get an error:

> Unknown error:
> _get_item_play_url() takes at most 5 arguments (6 given). Please try again

This error came after 40 min of playback, then all the files in OneDrive had the error message above. 

Thank you for your time!

**Comment by cguZZman** [comment]
@onutz your common drive module is not updated. Don't mix different issues since it has nothing to do with the reported here.

**Comment by onutz** [comment]
First it worked for 40 min, then it stopped and gave me this message. I have updated the sh*t out of it, reinstall it as new, reconfigured and it's still not working. Should I post in a separate thread now?

**Comment by cguZZman** [comment]
Create a new issue and post your debug log file.
I updated the original post in the forum with the info if you want to donate. https://forum.kodi.tv/showthread.php?tid=228443

**Comment by onutz** [comment]
I have donated. Now you fix it based on the error I copied, as I'm not a beta tester to share logs :))

**Comment by cguZZman** [comment]
I have refunded your donation. It does not work like that. 
The work I do here is to share my addon for free, and if you want to donate, you are welcome to do so. But no strings attached.
If you want to report a bug, the debug log file is required. Period.

**Comment by onutz** [comment]
No attachment from either sides, boss

**Comment by cguZZman** [comment]
test again and create a new ticket if the problem persists
