### ISSUE TITLE
Onedrive Addon: Onedrive content not showing as source

### ISSUE THREAD

**Issue by masca90021** [cguZZman/plugin.onedrive#23]
When adding Onedrive account as source, the folder remains empty, nothing shows in Kodi. The addon is properly configured and the account linked.

https://pastebin.com/c8PU2PzE

ADDON ADDED AS SOURCE IS EMPTY:

![Untitled](https://user-images.githubusercontent.com/57955748/69218375-4c766f80-0b79-11ea-99f3-30bc1a5acbbc.jpg)

ADDON CONTENTS: 

![Untitled1](https://user-images.githubusercontent.com/57955748/69218640-d292b600-0b79-11ea-91fc-b17f32ca1945.jpg)
![Untitled2](https://user-images.githubusercontent.com/57955748/69218641-d292b600-0b79-11ea-9bd2-aa9999841a9e.jpg)
![Untitled3](https://user-images.githubusercontent.com/57955748/69218642-d292b600-0b79-11ea-85ac-51d0923fc31c.jpg)

**Comment by cguZZman** [comment]
@masca90021can you upload your log again? I wasn't able to see it and it's removed now.

**Comment by masca90021** [comment]
I will upload it tomorrow when I get home from work.

**Comment by masca90021** [comment]
@cguZZman  https://jpst.it/1WVPy

**Comment by cguZZman** [comment]
I don't see any valid request made to the addon. Requests must be made to the addon source url:
localhost:<port>/source/OneDrive/
Add the correct source url, and if it's correct, even before adding it, you will be able to navigate the folders to select the one you want to add to Kodi.
Another issue I see is your account name. It's blank. I don't think that is supported for the source mode. So just put a name to your account. Name should appear in Kodi once is set.

**Comment by cguZZman** [comment]
Let us know if your problem was solved by doing those two things mentioned.
I'll close this issue. If you find a valid bug, I'll reopen this.

**Comment by masca90021** [comment]
Thanks for your answer, it seems that the lack of name on the account was the issue.
