### ISSUE TITLE
Seeing Error: no module named clouddrive.common.ui.addon

### ISSUE THREAD

**Issue by seanmcne** [cguZZman/plugin.onedrive#24]
**Describe the bug**
Unable to use Onedrive personal folder with images as source image for a screensaver plugin. 

**To Reproduce**
1. I was able to add an account
2. I downloaded the screensaver plugins 
3. set the image source to a folder, selected Onedrive, then selected a folder with about 100 images in it. 
4. when the screensaver loads I get this error 

**Your debug log file**
I can get this later but haven't had a chance to do that yet, I'm hoping this is something common that I've somehow missed.  If not let me know and I can get more logs.

**Comment by cguZZman** [comment]
Please upload your log so I can have an idea where to look on once I have time to review it.

**Comment by seanmcne** [comment]
https://paste.kodi.tv/witukiguwe 

The scenario is: 
- I have a folder in onedrive that contains images 
- I want to have a screensaver addon (either the one below or Kodi's gallery screensaver) access that onedrive folder to display the images randomly/in a loop. 

How i reproduced this on a clean installation on a raspberry pi 3:
1. Installed Kodi addons for Onedrive and installed the two screensaver addins 
2. Configured Onedrive and logged in 
3. then went into https://kodi.wiki/view/Add-on:Picture_Slideshow_Screensaver Picture SlideShow.  
4. Selected image folder, selected onedrive, went into Files, Pictures, SlideshowFolder then pressed OK to select that folder 
5. Waited 1 minute for the screensaver timeout to hit and load the screensaver 
6. then i see this error (picture below) 

![image](https://user-images.githubusercontent.com/2292260/70102299-4e224780-15fd-11ea-80c8-756fc2a38245.png)

**Comment by cguZZman** [comment]
Ok, looks like the screensaver addon is calling the OneDrive addon package folder and trying to execute it as a program, directly, which it won't work (obviously) as you can see. 
It's an issue with that screensaver addon.

A workaround could be: Instead of adding a folder from the addon directly, add OneDrive as a source in Kodi and then add a folder from that source to your screensaver addon.

**Comment by seanmcne** [comment]
Thanks for the response, I've tried using the source on two screensavers now and both do not work with a network source unfortunately :(  

not sure if it's my current version of Kodi being buggy or what's going on but I think I'll have to look elsewhere for how to build a gallery slideshow picture frame (Kodi appears to be overkill) but I like the look of your onedrive sync/connector - great work on this!  It's too bad Kodi makes it so difficult to configure & use, thanks for your time and help!
