### ISSUE TITLE
Eats up all memory on kodi 18.x (raspbian/buster and LibreElec)

### ISSUE THREAD

**Issue by orgi** [cguZZman/plugin.onedrive#25]
I'm not 100% sure whether this is related to the OneDrive plugin - however this is my last hope.
Background: Everything was working just fine some months ago running kodi 17.x on raspbian/stretch.  Did an update to buster yesterday.

Now I got issues playing video files located on my OneDrive. Smaller files will play, larger ones (Full HD) won't play but will render the raspberry useless.

Checking the memory usage shows that all the memory will get used including swap space (overall at about 150 - 200 MB) - although caching in Kodi is set to 20MB max.

As playing local stream is just working fine I suspect that there's additional caching done when using the OneDrive plugin. Now it seems that it tries to use more RAM than available.

Please let me know whether there's any caching involved somewhere.

Btw.:
Tried on PI 1, PI1B using raspbian buster and LibreELEC 9.2.0.

**Comment by orgi** [comment]
to confirm I now disabled all buffering in kodi in `advancedsettings.xml`. Trying to play a full hd video file located on my OneDrive would still eat up all memory:

```xml
<advancedsettings>
  <cache>
    <memorysize>
      20971520
    </memorysize>
    <buffermode>
      3
    </buffermode>
  </cache>
</advancedsettings>
```

**Comment by orgi** [comment]
Update: Using `rclone` to mount the onedrive works like a charm.

**Comment by cguZZman** [comment]
The addon does not cache or do anything else with your video other than discovering the URL and hand it to Kodi to be played. I tested the raspberry once with a 1080p video and it sucked. So I would say you need to get a better device to play higher definition videos. 
If rclone it's working for you, I'm glad. But there is nothing else the addon can do.
