### ISSUE TITLE
Kodi 19

### ISSUE THREAD

**Issue by Janasek** [cguZZman/plugin.onedrive#27]
are there any chances for the add-on to be compatible with kodi 19

thanks

**Comment by cguZZman** [comment]
you can test it and let me know the errors you found by creating an issue with all the info required

**Comment by Janasek** [comment]
what should i write
are you not using kodi 19? 
kodi 18 python
 kodi 19 another version of python


https://paste.kodi.tv/isabuloqom.kodi
