### ISSUE TITLE
Videos won't play 

### ISSUE THREAD

**Issue by Curtmcgirt** [cguZZman/plugin.onedrive#28]
Kodi on multiple fire tv sticks, installed with "easy fire tools," onedrive add on installs fine, I can see my directories and videos, but a four minute 720p mp4 buffers for about four minutes, and then freezes a few seconds after it starts playing. If it even starts playing. 200mbps download speed as tested from the fire tv stick. Tried some YouTube suggestions about refresh rate and this and that advanced setting. Zero change. These aren't HD feature films, these are 1-15 minute snippets of home movies.

As a comparison, I Downloaded kodi and the onedrive add-on to my galaxy s 9 plus. same exact issues watching onedrive videos inside kodi. But I have no issues watching the same onedrive videos in the Android onedrive app. I have no issues streaming videos from Netflix, YouTube, or any other streaming service on this phone or on the fire tv sticks. 

Am I doing something wrong?

**Comment by cguZZman** [comment]
The first thing you did wrong was not posting all the required information, including your debug log file, to create this issue.
Anyway, the addon does not play the video, Kodi does. Sounds like your Kodi version has a problem. Read this post https://github.com/cguZZman/plugin.googledrive/issues/67, sounds like a similar problem.

**Comment by Curtmcgirt** [comment]
thanks for the reply, yes it occurred to me that kodi was the issue after i posted. kodi 18.5. further testing revealed my galaxy performed noticeably better than the fire tv stick. i also tried using mobile data in case time warner is throttling something. inconsistent results. i may try downgrading kodi on one of the fire sticks. for what it's worth, i downloaded [some other unofficial kodi video add-on] to one of the fire tv sticks. while the menus and search were terribly slow, once a movie actually started playing, it was fine. i watched 20 minutes of a 720p movie with no buffering. later,i set up a nas with a raspberry pi, and loaded some of the same onedrive home movies onto that nas. kodi played those movies from smb://thatnas/folder/ instantly.
