### ISSUE TITLE
Videos dont play anymore since some days - "takes at most 5 arguments"

### ISSUE THREAD

**Issue by The-Dewd** [cguZZman/plugin.onedrive#29]
Hi cguZZman, 

First I would like to thank you for providing this amazing plugin, which I was using without any problems since years! 

Since some days it wont play my video files anymore, always giving me this message:
_Unknown error:
_get_item_play_url() takes at most 5 arguments (6 given) 
Please try again._

I tried it on my 2 shield android TV boxes as well as on my Windows 10 laptop. 

The files giving me the error message are MKV extensions. Tried some AVI and MP4 too: Those just dont play anymore, but without error.

Anything I can do about this?

Let me know if you need further information from my side please.

Again thanks for the great work!

https://paste.kodi.tv/refajaqeco = logfile

[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/4243538/kodi.log)
![2020-02-24 08_36_04-Kodi](https://user-images.githubusercontent.com/61406493/75136684-b9a02080-56e5-11ea-95be-969bab113df0.jpg)

**Comment by cguZZman** [comment]
thanks for the report. Will fix it soon.

**Comment by The-Dewd** [comment]
You are the best!! Thanks again and also for this add-on, its really valuable to me!

**Comment by cguZZman** [comment]
Fix is in my repository now, or you can wait until Kodi publish the update in its repository.
Update is only in the Cloud Drive Common Module addon, version1.2.11
