### ISSUE TITLE
_get_item_play_url() takes at most 5 arguments (6 given) error with subtitles

### ISSUE THREAD

**Issue by cblogins** [cguZZman/plugin.onedrive#30]
**Describe the bug**
When the "set subtitles from cloud drive" option in the addon settings is enabled the following error is thrown when attempting to play a movie:
Unknown error: _get_item_play_url() takes at most 5 arguments (6 given) Please try again.
The attempt is then aborted by kodi and the movie can't be played.

**To Reproduce**
1. In the onedrive addon settings enable "set subtitles from cloud drive"
2. Try to play a movie with a correctly named .srt file in the cloud folder.

**Your debug log file**
https://paste.kodi.tv/ezamobirib.kodi
error at 2020-02-28 11:08:51.845

Setup: On kodi 18.5 on raspbian I exported .strm files to a home folder and added that folder to the library. When disabling the option "set subtitles from cloud drive" in the plugin settings, no error occurs and the movie/file is played correctly without any problems.

Let me know, if you need further information.

Thanks and regards,
C

**Comment by cguZZman** [comment]
Thanks for the report. It was already reported in #29 and is already fix. Just waiting for the kodi team to publish it.
You can get the fix now from my repository.

**Comment by cblogins** [comment]
Hi Carlos,
my apologies, I checked the open issues, but not the closed ones... my bad :)
So thanks for the fix and I'd like to quote The-Dewd with "thank you for providing this amazing plugin" and again kindly ask, if there's any donation information.

All the best and kind regards,
C

**Comment by cguZZman** [comment]
No problem. 
Here is the link where you can donate: [paypal.me/cguzzman](https://www.paypal.me/cguzzman)
Thanks
