### ISSUE TITLE
Cannot add account

### ISSUE THREAD

**Issue by ForestPCT** [cguZZman/plugin.onedrive#35]
Have added your Onedrive add on to Kodi. Try to add my account but the generated code is not recognised when I enter it at https://drive-login.herokuapp.com. Tried using QR code and by going to url direct. Any tips please?
Tx

**Comment by cguZZman** [comment]
Make sure the source id you see in kodi is the same displayed in the login page. If they are not the same, you are using different networks and that is the reason.
