### ISSUE TITLE
invalid code

### ISSUE THREAD

**Issue by JoTomspot** [cguZZman/plugin.onedrive#36]
Raspberry Pi 4 B - Kodi - LibreElec

I have a Onedrive account and can't connect - I always get the error message "Your code is invalid. Make sure you entered the code displayed in Kodi and you're in the same network as your kodi device.".

Both Kodi and the laptop through which I enter the code are in a wired network. I use a fixed IP 62.195.168.58. Is it necessary to switch off VPN? Plugin version is 2.1.6. 

What type of log can I provide?

**Comment by cguZZman** [comment]
You dont need a vpn to use the addon. In any case it should not matter as long as both devices are connected to internet with the same public ip. 
If your problem persist, post your debug log file and will reopen this issue.
