### ISSUE TITLE
Error on opening and listing OneDrive files and directories

### ISSUE THREAD

**Issue by gabriellluz** [cguZZman/plugin.onedrive#37]
**Describe the bug**
When I try to list and play OneDrive files, I get an error with the following message:
_"Uknown error:
Extra data: line 23 column 5 - line 24 column 2 (char 2176 - 2179)
Please try again."_

**To Reproduce**
1. Open OneDrive addon
2. Try to open an account link
3. As soon as it starts opening an OneDrive dir, I get the message above.

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.
http://paste.kodi.tv/casujarove

**Screenshots**
![Uploading IMG_20200704_151024.jpg…]()

**Comment by cguZZman** [comment]
same as https://github.com/cguZZman/plugin.onedrive/issues/16. 
working on the fix finally. in the meantime check there for the workaround.
