### ISSUE TITLE
Video cannot be played in video add-on from Onedrive

### ISSUE THREAD

**Issue by leshafiq** [cguZZman/plugin.onedrive#38]
**Describe the bug**
All video cannot be played . An error pop out:

                          "Something went wrong with this operation.
                                        Response <Exception>: {

                                          "error": {

                                            "code": "badArgument",

                                            "message": "One of the provided arguments is not acceptable.",

                                            "innerError": {

                                              "date": "2020-07-28T06:40:14",

                                              "request-id": "b1bba6a5-c7fb-41c4-bca4-f15a4fd98f7c"

                                            }

                                          }

                                        }
                                        Please try again later."

**To Reproduce**
1. Go to 'Onedrive account'
2. Click on 'Any video file'
3. See error or issue

**Your debug log file**
[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/4995174/kodi.log)

**Screenshots**
![88623481-9f74cf00-d0d7-11ea-9329-a216ca626273](https://user-images.githubusercontent.com/68889041/88807362-36c74880-d1e4-11ea-8129-a1614fb7a491.png)

**Comment by cguZZman** [comment]
It is failing when trying to search for the subtitle file.
But first thing, you don't have the latest version of the Cloud Drive Common Module. Latest version is 1.2.15 and you have 1.2.12.
Update the module by installing my repo and then test again.

**Comment by leshafiq** [comment]
> It is failing when trying to search for the subtitle file.
> But first thing, you don't have the latest version of the Cloud Drive Common Module. Latest version is 1.2.15 and you have 1.2.12.
> Update the module by installing my repo and then test again.
> 
> Also, can you tell me the type of account? If is business, can you test in the personal account?

Hi, thanks for replying. I have just updated the module but it still have the same problem.
I'm using a business account (student account) since it have free storage. I have been using the same account for a year and it run smoothly. I still have no idea what's wrong.

**Comment by cguZZman** [comment]
For some reason it's working for me, but I only have a personal account for now.

Can you go to this file:
`C:\Users\<your_user>\AppData\Roaming\Kodi\addons\plugin.onedrive\resources\lib\provider\onedrive.py`

And then modify the line 188.
This should be the exact text on that line:
`search_url = '/drives/'+item_driveid+'/items/' + parent + '/search(q=\''+urllib.quote(Utils.str(Utils.remove_extension(name)).replace("'","''"))+'\')'`

I need you to replace it with this exact line:
`search_url = '/drives/'+item_driveid+'/root/search(q=\''+urllib.quote(Utils.str(Utils.remove_extension(name)).replace("'","''"))+'\')'`

Save the change on the file, and then try playing your video again.

If still not working, please attach your debug log file again.

**Comment by leshafiq** [comment]
> For some reason it's working for me, but I only have a personal account for now.
> 
> Can you go to this file:
> `C:\Users\<your_user>\AppData\Roaming\Kodi\addons\plugin.onedrive\resources\lib\provider\onedrive.py`
> 
> And then modify the line 188.
> This should be the exact text on that line:
> `search_url = '/drives/'+item_driveid+'/items/' + parent + '/search(q=\''+urllib.quote(Utils.str(Utils.remove_extension(name)).replace("'","''"))+'\')'`
> 
> (maybe here in github appears as two lines, but it is a single line after you copy and paste it)
> 
> I need you to replace it with this exact line:
> `search_url = '/drives/'+item_driveid+'/root/search(q=\''+urllib.quote(Utils.str(Utils.remove_extension(name)).replace("'","''"))+'\')'`
> 
> Save the change on the file, and then try playing your video again.
> 
> If still not working, please attach your debug log file again.

I have tried wih your method but it is still not working
![image](https://user-images.githubusercontent.com/68889041/88870403-da961000-d247-11ea-856a-7d9b0b3511ad.png)

Here is the debug log file:
[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/4998276/kodi.log)

**Comment by cguZZman** [comment]
I'm unable to reproduce the same error and I don't have a business account to better test it but will try to get one.
In the meantime, you will have to disable the option "Automatically set subtitles from cloud drive" in the addon settings if you want to at least play the videos. This would be the workaround for now.

As a last test, can you do a search over your drive? Go to your list of accounts and in the context menu there is an option "Search...". Do a search of anything and let me know if it works. And if it works, navigate to any folder in your drive and do the same search. Let me know the results if you can. Thanks.

**Comment by leshafiq** [comment]
> I'm unable to reproduce the same error and I don't have a business account to better test it but will try to get one.
> In the meantime, you will have to disable the option "Automatically set subtitles from cloud drive" in the addon settings if you want to at least play the videos. This would be the workaround for now.
> 
> As a last test, can you do a search over your drive? Go to your list of accounts and in the context menu there is an option "Search...". Do a search of anything and let me know if it works. And if it works, navigate to any folder in your drive and do the same search. Let me know the results if you can. Thanks.

Looks like disabling the option "Automatically set subtitles from cloud drive" does work. Thank you so much.

Do you mean this: 
![image](https://user-images.githubusercontent.com/68889041/88999589-8cf0d480-d327-11ea-83b7-caa9b9556e76.png)
![image](https://user-images.githubusercontent.com/68889041/88999606-95e1a600-d327-11ea-8601-b74bfec75692.png)

**Comment by 0x2f0713** [comment]
>
> Looks like disabling the option "Automatically set subtitles from cloud drive" does work. Thank you so much.
>
Thank you for your solution, I have same problem
