### ISSUE TITLE
kodi one-drive

### ISSUE THREAD

**Issue by dvasugithub** [cguZZman/plugin.onedrive#39]
the videos are not playing anymore.

getting error,

please try again later.
error:
code: bad argument
message: one of the provided arguments is not acceptable.

**Comment by cguZZman** [comment]
post your debug log file and all the required information. will reopen it once you do it.

**Comment by dvasugithub** [comment]
[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/5104721/kodi.log)
