### ISSUE TITLE
OneDrive for Business is empty

### ISSUE THREAD

**Issue by jpdribbler** [cguZZman/plugin.onedrive#4]
Hi cguzzman,

first of all thank you for this amazing addon!

I could add my office 365 one drive business account (version 1.31) without any problem but unfortunately i cannot see any files under Videos, there are no folder or files at all. It shows the account but the next step is emtpy. I can give you my credentials if you need to test office 365 (i think right now you can get 1 year for free as developer) See https://profile.microsoft.com/RegSysProf...&lcid=1033

Hardware: Shield TV
Kodi Fork SPMC 16.6.0 (not compatible?)

Thank you again. (This post has been created in the forum https://forum.kodi.tv/showthread.php?tid=228443&pid=2630901#pid2630901 as well, thanks)

**Comment by tonystam** [comment]
Hello cguzzman,

Thanks for this Add-on. I have exactly the same issue, any solution?

Thanks!

**Comment by cguZZman** [comment]
Issue has been resolved in version 2.0.0. 
Just waiting for the Kodi team to merge it in the repo.
Will keep it open until the merge is done.

**Comment by jpdribbler** [comment]
Christmas came early! Many thanks carlos. I will try it on the weekend and i will give feedback. Thanks a lot. Feel free to use my onedrive acc as soon as it lasts :)
