### ISSUE TITLE
4k 2160p videos streaming issue

### ISSUE THREAD

**Issue by pitbzury** [cguZZman/plugin.onedrive#43]
Looking out for a solution because it starts sometimes for 5 seconds  then it buffer and crash kodi( mostly not at all)
Model of my android tv : Beelink Gt1 Ultimate, connexion speeds with device : 340-400Mb Down and UP.

Known that MKV format is not supported by microsoft, but does for  mkv 1080p .

Sorry if it is considered as not an issue, but I think It should help some other folks too.

Thanks

**Comment by akhil-rana** [comment]
Works for me in 2160p 10bit HDR x265 on android TV

**Comment by cguZZman** [comment]
The addon does not handle formats or types of videos. Kodi does. 
I would suggest to test it with other devices and/or different formats.
