### ISSUE TITLE
Kodi 19 Support 

### ISSUE THREAD

**Issue by akhil-rana** [cguZZman/plugin.onedrive#44]
**Is your feature request related to a problem? Please describe.**
Can't use onedrive with kodi 19. App automatically got updated yesterday from playstore and addon doesn't exist anymore

**Comment by cguZZman** [comment]
Kodi 19 is still beta. A version of the addon that works with version 19 will be ready by the time is released.

**Comment by treanord** [comment]
> Kodi 19 is still beta. A version of the addon that works with version 19 will be ready by the time is released.

let us know if you are looking for any beta testers ;)

**Comment by cguZZman** [comment]
It would be nice. 
The version compatible with Kodi 19 is available now. Just install my new repository for matrix from here https://github.com/cguZZman/repository.plugins

**Comment by treanord** [comment]
> It would be nice.
> The version compatible with Kodi 19 is available now. Just install my new repository for matrix from here https://github.com/cguZZman/repository.plugins

Cool, thanks!

I've added it to my laptop to test and can browse my OneDrive and play files directly but adding as a source (http://localhost:8586/source) doesn't seem to work. I'll try one of my android devices over the weekend just in case it's a Windows issue.

**Comment by cguZZman** [comment]
good catch. there is a new version now. 
can you try again?

**Comment by treanord** [comment]
> good catch. there is a new version now.
> can you try again?

Not yet seeing a new version. Will check again in the morning. Many thanks :)

**Comment by treanord** [comment]
still only seeing the version from Nov 13

**Comment by cguZZman** [comment]
check now

**Comment by treanord** [comment]
> check now

still seeing the same version. tried uninstalling and installing again - no change

**Comment by cguZZman** [comment]
it should be working fine by now. 
it is also available in the Kodi Repository.

**Comment by treanord** [comment]
Just tested on beta 2. Looks good!  Many thanks!

**Comment by akhil-rana** [comment]
When I updated my app on android, the old addon got removed by itself because of kodi 19.

Now that it is available in the official repository, will it be automatically updated too if I update from v18 to matrix? Or do I have to set it up again?

**Comment by cguZZman** [comment]
no idea. that would be a kodi feature.
I would say, test it and let us know.
