### ISSUE TITLE
Playback ends early

### ISSUE THREAD

**Issue by patrickrushton** [cguZZman/plugin.onedrive#46]
**Describe the bug**
Videos stop playing a few minutes before the end. It doesn't happen if I manually fast forward to near the end of the video, but if watching from the beginning, it will stop early.

**To Reproduce**

1. Play a 30 minute video from a OneDrive Business account. 
2. It will stop playing around the 28 minute mark and return to the menu as if it has reached the end of the show.
3. Take cover while child has tantrum because he missed the ending of his favourite show.

**Your debug log file**
I'm running the latest Kodi on an Android TV which won't let me get a debug log unfortunately. 

**Screenshots**

**Comment by cguZZman** [comment]
sounds similar to https://github.com/cguZZman/plugin.onedrive/issues/22, but I need the debug log file to take a look on it.
you can install the logfile uploader addon to help with that. 
https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by ti-font** [comment]
I have the same issue on OSMC on a RPi 3.
About 2 minutes before the end of the video it cuts off.
I installed the log uploader. I will post a debug log once it happens again!

**Comment by ti-font** [comment]
It seems to happen when you don’t forward or rewind during a video. If you do, it plays until the the end.
Here’s my log, just happened again:

https://paste.kodi.tv/kivopelipo

**Comment by cguZZman** [comment]
Good to know that is reproducible. I have been trying to reproduce it but seems to work fine on my end.
Now, about your log file, it does not contain any debug information. Enable debug logging first (Settings > System > Logging > Enable debug logging) and if possible, also select libcURL libary in the "Specify component-specific logging...".
Then try to make it happen again.

**Comment by cguZZman** [comment]
you can ignore enabling specific logging for libcURL. 
it could make your debug log file bigger than 1 MB and Kodi Logfile Uploader will deny the upload of the file.

**Comment by ti-font** [comment]
Ok, I enabled the debug logging. I will try to reproduce later today.

**Comment by ti-font** [comment]
Here’s the log:
https://paste.kodi.tv/sewaqonaga

**Comment by cguZZman** [comment]
Looks like an issue either in Kodi or the curl library. In both cases, is out of the reach of the addon.
This is the error: 
`2020-12-15 01:02:40.984 T:1043185888   ERROR: CCurlFile::FillBuffer - Failed: Stream error in the HTTP/2 framing layer(92)`
At this point, the addon was not interacting with Kodi. Kodi was playing the URL from onedrive, given by the addon 40 minutes ago, and suddenly the error.
Can you try with the beta version of Kodi 19? It is possible that a new version of curl is used there and/or the issue was already fixed.
