### ISSUE TITLE
"Shared with me" folders unavailable when using OneDrive as a source

### ISSUE THREAD

**Issue by marcogallardos** [cguZZman/plugin.onedrive#47]
When OneDrive is added as a source, the root folder is "Files", bypassing the selection screen (visible using the plugin directly and not as a source) where "Shared with me" folders are located.

If a "Shared with me" folder is added to my own OneDrive account using "Add to my OneDrive" to make it visible as a regular folder, it appears blank and can't be used as a source.

**Comment by cguZZman** [comment]
"Shared with me" folder is not implemented as a source.
Added to your drive should work. Create a new issue with your debug log file when getting the blank page.
