### ISSUE TITLE
No subtitle bug

### ISSUE THREAD

**Issue by Gjur0** [cguZZman/plugin.onedrive#48]
**Describe the bug**

**To Reproduce**
4. See error or issue

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by Gjur0** [comment]
Hi, I have still problem with plugin it doesn't pull the subtitle out of onedrive bussines. Can you please check it?

**Comment by cguZZman** [comment]
There is no much to do without the required information.
Create a new issue and attach all required information.
