### ISSUE TITLE
NEF files

### ISSUE THREAD

**Issue by Fisherman5020** [cguZZman/plugin.onedrive#50]
**Describe the bug**
My Onedrive pictures repository has almost 50.000 files in several hundred folders. Can't see raw photos (Nikon NEF files), neither run a recursive presentation on the full database

**To Reproduce**
4. See error or issue

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by cguZZman** [comment]
No debug log file, no steps to reproduce it. Open a new issue with all required information.
