### ISSUE TITLE
Subtiles not working in OneDrive Plugin v2.2.8 in Kodi

### ISSUE THREAD

**Issue by Sam8484** [cguZZman/plugin.onedrive#53]
I have videos and subtitle files (.srt) and correctly named same in the same folder. OneDrive plugin  v2.2.8 fails to display them. I do have same files stored locally on hard disk also and if played thro' hard disk subtitles display well. Subs are encode with UTF-8 with BOM. The issue is in OneDrive plugin and this issue is an unresolved issue since long time. The video file work perfectly with subs embedded in .mkv but does not work when place separately in the folder with the same name as video file. Tried in kodi 18.9 and kodi 19 but no result.

**Comment by cguZZman** [comment]
Try with the latest version and provide a debug log file.
