### ISSUE TITLE
Kodi freezes when seeking video from OneDrive

### ISSUE THREAD

**Issue by rodolfostanic** [cguZZman/plugin.onedrive#56]
**Describe the bug**
Every time I try to seek the video to another position, Kodi freezes. This behavior occurs in different videos and codecs, with or without subtitles. Ocasionally, the video plays partially before freezing.

**To Reproduce**
1. Go to 'Add-ons'
2. Click on 'OneDrive'
3. Load a video file.
4. Place the video's playhead at any position by clicking on the timeline.
5. Loading circle with 100 written in it stays on screen and nothing happens. Clicking on the stop button freezes Kodi.

**Your debug log file**
[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/6730038/kodi.log)

**Comment by OsoaGitHub** [comment]
Same issue here

**Comment by cguZZman** [comment]
It is not clear for me why is freezing, but you can try disabling http2 advancedsettings.xml:
```
        <network>
          <disablehttp2>true</disablehttp2> 
        </network>
```
This is an issue between Kodi and OneDrive server anyway.

**Comment by OsoaGitHub** [comment]
> 
> 
> It is not clear for me why is freezing, but you can try disabling http2 advancedsettings.xml:
> 
> ```
>         <network>
>           <disablehttp2>true</disablehttp2> 
>         </network>
> ```
> 
> This is an issue between Kodi and OneDrive server anyway.

This has worked for me, are there any disadvantages to this?

**Comment by cguZZman** [comment]
No disadvantages as of now.
