### ISSUE TITLE
Bunch of issues

### ISSUE THREAD

**Issue by OsoaGitHub** [cguZZman/plugin.onedrive#57]
I described all of the issues [here](https://www.reddit.com/r/kodi/comments/ogd4ia/issues_with_onedrive_addon/)

**Comment by OsoaGitHub** [comment]
Ok, the videos crashingseems to be fixed by installing the plugin from [this](https://github.com/cguZZman/repository.plugins) repo instead of official, then resetting my config by going through it again, disabling subtitles and clearing cache. I will report back after a while to see if it is a false alarm or not.

**Comment by OsoaGitHub** [comment]
Nvm it's not fixed, just crashed a lot later (like 10 minutes instead of 1-5). It does seem to be an error with `script.module.clouddrive.common` though, so I've reported an issue on that page

**Comment by cguZZman** [comment]
Let's track the issue here. I need all the information as required in the issue template.

**Comment by OsoaGitHub** [comment]
Ok, it seems that disabling http2 like in #56 fixes it

**Comment by cguZZman** [comment]
great
