### ISSUE TITLE
Double authentication support

### ISSUE THREAD

**Issue by Tecknoth** [cguZZman/plugin.onedrive#61]
**Is your feature request related to a problem? Please describe.**
It is possible to enable a double factor authentication through microsoft accounts double authentication. But the addon doesn't seem to support this kind of authentication scenario. Thus trying to add an account with double authentication enabled ends up with a 401 error (not authenticated).

**Describe the solution you'd like**
Improve the current mechanism to support multi factor authentications.
![01 - Double authentication request](https://user-images.githubusercontent.com/47478286/146807494-f1c5575b-06b7-4038-808f-f2a22692820a.png)

**Comment by cguZZman** [comment]
The addon has nothing to do with that, but in any case, this is working. There is nothing different with accounts with MFA.
