### ISSUE TITLE
Videos are not playing anymore - Onedrive on Kodi 

### ISSUE THREAD

**Issue by The-Dewd** [cguZZman/plugin.onedrive#63]
Hi cguZZman,

Thanks so much for providing this great service since many years, I am a daily user and more than grateful for this!!

**Describe the bug**
Since a couple of days, maybe a week, I cant play anymore videos from my onedrive folders. I tested it both on my Shield TV and on my Windows 11 PC with Kodi. Either the video does not start or it stops after 5-10 seconds, freezing the whole Kodi player.

I uninstalled Kodi, cleared the cache, installed the plugin from scratch, no change unfortuantely. 

Probably the problem is on the onedrives side, but I have no other connected player to test this. Could you please have a look if there is a way fixing this? 

Many thanks in advance!!

**To Reproduce**
4. See error or issue

**Your debug log file**
https://paste.kodi.tv/gojahejoxo

**Screenshots**

**Comment by cguZZman** [comment]
Disable http2 in advancesettings.xml

**Comment by The-Dewd** [comment]
Welcome back and many thanks Guzzman! Glad to see your reply...

I could not locate the file advancesettings.xml, neither on my android TV, nor on the PC Kodi installation. Unfortunately I am stuck getting this fixed... Is there any other way to repair this problem?

**Comment by t0mtee** [comment]
> Welcome back and many thanks Guzzman! Glad to see your reply...
> 
> I could not locate the file advancesettings.xml, neither on my android TV, nor on the PC Kodi installation. Unfortunately I am stuck getting this fixed... Is there any other way to repair this problem?

you need to look for advancedsettings.xml - [this](https://kodi.wiki/view/Advancedsettings.xml) page has instructions on how to locate the file.
