### ISSUE TITLE
Server down 

### ISSUE THREAD

**Issue by jamos316** [cguZZman/plugin.onedrive#65]
Hi

Get an error showing 'The Server is temporarily unavailable for this operation'. Was working yesterday.
Kodi 19.4, using onedrive downloaded from kodi addon repo. Have also tried reinstalling 

James

**Comment by boype** [comment]
Same problem here. Kodi 19.3 on Android TV

**Comment by cguZZman** [comment]
Heroku removed the free tier server service. I'm looking for a new service. It will be down in the meantime.

**Comment by jamos316** [comment]
Thanks for the reply. Keep us notified here if you will please

**Comment by cguZZman** [comment]
Read my full response here: https://forum.kodi.tv/showthread.php?tid=324784&pid=3120043#pid3120043

**For now on, the server will be up as long as the community donates and help with the cost of the hosting.** If you are using the addon, don't be shy - any amount will help.
