### ISSUE TITLE
error when try to add an account Kodi 20

### ISSUE THREAD

**Issue by JohnJohn45** [cguZZman/plugin.onedrive#66]
Hi,
When I try to add an account in Kodi 20 I have this error :
Unknown error:
module 'inspect' has no attribute 'getargspec'
Please try again.

Thank you for your excellent addon

**Comment by peno64** [comment]
See https://github.com/cguZZman/plugin.googledrive/issues/302

**Comment by cguZZman** [comment]
Install my repository and install the latest version from it.

**Comment by gersonjunior87** [comment]
The error is still occurring to me.

**Comment by gersonjunior87** [comment]
> Install my repository and install the latest version from it.

How can I install your repository ?
