### ISSUE TITLE
while adding account (unknown error)

### ISSUE THREAD

**Issue by hamidsaeed13** [cguZZman/plugin.onedrive#67]
module 'inspect' has no attribute 'getargspec'
Please try again.

**Comment by Kevster65** [comment]
Yes I’m getting the same on Kodi 20

**Comment by peno64** [comment]
Same as https://github.com/cguZZman/plugin.onedrive/issues/66

**Comment by gersonjunior87** [comment]
Same here

**Comment by Gundi17** [comment]
Same here. I am using Kodi on Android TV and the problem started right after Kodi updated to v20.

**Comment by andy-in-worthing** [comment]
Same. Coincided with my Raspberry Pi (runs TVHeadend) needing a new SD card so was off Kodi for a few days, just reincarnated it and Android TV version moved from Matrix to Nexus.

**Comment by dvasukodi** [comment]
same here

**Comment by DeHickok** [comment]
Same here... Sony Android TV, Kodi 20, somebody reported that it was resolved few hours ago but, still, after reinstallation of whole KODI+OneDrive AddOn same error

**Comment by cguZZman** [comment]
Install my repository and install the latest version from it.
