### ISSUE TITLE
Dependency could not be satisfied

### ISSUE THREAD

**Issue by coffeesurfers** [cguZZman/plugin.onedrive#69]
When installing the kodi 20 fix on a nvidia shield tv 

https://github.com/cguZZman/plugin.onedrive/tree/9c9704c60345f976336dcfeea9f59b81614608bd

The moment the zip file is selected results in the error
https://youtube.com/shorts/vlrzIDI9W_4?feature=share

**Comment by cguZZman** [comment]
Don't install it manually. Install it from my repository or Kodi's repository.
