### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired

### ISSUE THREAD

**Issue by t0mtee** [cguZZman/plugin.onedrive#72]
**Describe the bug**
I'm unable to access my OneDrive account in any way.

**To Reproduce**
1. Go to the OneDrive addon
2. Try to add your account
4. See error or issue

**Your debug log file**
[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/10935081/kodi.log)

**Comment by TinyRick1489** [comment]
> **Describe the bug** I'm unable to access my OneDrive account in any way.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to the OneDrive addon
> 2. Try to add your account
> 3. See error or issue
> 
> **Your debug log file** [kodi.log](https://github.com/cguZZman/plugin.onedrive/files/10935081/kodi.log)

1. Open this link in your browser - https://graph.microsoft.com/v1.0/me/
2. Click on the padlock icon on the address box and export the certificate in .der format
3. Install that certificate
4. Reboot your system and then start Kodi

**Comment by t0mtee** [comment]
> > **Describe the bug** I'm unable to access my OneDrive account in any way.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to the OneDrive addon
> > 2. Try to add your account
> > 3. See error or issue
> > 
> > **Your debug log file** [kodi.log](https://github.com/cguZZman/plugin.onedrive/files/10935081/kodi.log)
> 
>     1. Open this link in your browser - [graph.microsoft.com/v1.0/me](https://graph.microsoft.com/v1.0/me/)
> 
>     2. Click on the padlock icon on the address box and export the certificate in .der format
> 
>     3. Install that certificate
> 
>     4. Reboot your system and then start Kodi

It worked! Thanks
